name: camaraygps
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.12
  path_provider: ^2.0.0
  video_player: ^2.7.0
  permission_handler: ^11.3.1
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  flutter_map: ^3.1.0
  latlong2: ^0.8.1
  camera: ^0.10.0+5
  image_picker: ^0.8.4+3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  build_runner: ^2.1.10
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
